# base_path : "D:/net_data_Tif"
# res_path : "D:/BraintoResult"
# to_mat_path : "D:/BraintoResult/tomat"
# batch_interp_base_path : "D:/net_data_Tif/data_takehalf_Tif"
# batch_interp_save_path : "D:/net_data_Tif/data_interp_Tif"

# base_path: "/mnt/no1/cui/brain_interp_256_data/"
# res_path: "/mnt/no1/cui/result1"
base_path: "/mnt/no1/cui/brain_interp_cubic_256_data"
res_path: "/mnt/no1/cui/result/"

# test_res_path: "/mnt/no1/cui/result1/UNetRegis"
model_test_path: "/mnt/no1/cui/result/UNetRegis/best_model.pth"
res_test_path: "/mnt/no1/cui/TestResult/UNetRegis"
# test_img_path: "/mnt/no1/cui/brain_interp_cubic_256_data/test_img"
# test_label_path: "/mnt/no1/cui/brain_interp_cubic_256_data/test_label"